language: node_js
node_js:
    - '0.10'
    - '0.11'
before_install:
    - currentfolder=${PWD##*/}
    - if [ "$currentfolder" != 'generator-gulpplugin-coffee' ]; then cd .. && eval "mv $currentfolder generator-gulpplugin-coffee" && cd generator-gulpplugin-coffee; fi
before_script:
    - npm config set coverage true
after_success:
    - npm run-script coveralls
env:
    - DEBUG="generators:*"
